spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: chattly2025@gmail.com
    password: chixnfryqqajmfer
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chattly?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: kim2580mi

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 674868739224-361fc2j97sia4571pcm7h2kjj5esd45v.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: email, profile

          kakao:
            client-id: cab73e2198671f581faaa858e7c569c1
            client-secret: vTKHRdywW7N6Pi4jCE0v2faUcOCNT085
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_image, account_email

          naver:
            client-id: dIfQmNdLvoFaE5oYiITA
            client-secret: CqIIzvHEQ9
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: email, profile_image
            client-name: Naver

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

cloud:
  aws:
    s3:
      bucket: chattly
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIA3IV73HJFRA3CIQVS
      secretKey: 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

jwt:
  secret-key: /anxrfRE8RuJtbqCLzdGdT/2AVmFmq4u6b+tQfRZpG6AVhN4CPanR9Vf+eRx3u9Y6xGQzpVY4ki8d5wEp6vTkw==
  access-header: Authorization-Access
  refresh-header: Authorization-Refresh

default:
  profile: https://refrigerator-cleaner.s3.ap-northeast-2.amazonaws.com/refrigerator-cleaner-default-profile.jpg